"""Deprecated compatibility exports for historical separator fitting."""

from __future__ import annotations

from warnings import warn

from ..inverse.separator import (
    ActiveSetIteration,
    ActiveSetOptions,
    ActiveSetPathSummary,
    AlgebraicEdgeDiagnostics,
    ConnectivityDiagnostics,
    ConnectivityDiagnosticsError,
    ConstraintGraphDiagnostics,
    ExponentialBoundaryPenalty,
    FitModel,
    FixedValue,
    HardConstraintConflict,
    HardConstraintConflictTerm,
    HuberLoss,
    Interval,
    L2Regularization,
    PairBisectorConstraints,
    PairConstraintDiagnostics,
    PowerFitBounds,
    PowerFitObjectiveBreakdown,
    PowerFitPredictions,
    PowerFitProblem,
    PowerWeightFitResult,
    RealizedPairDiagnostics,
    ReciprocalBoundaryPenalty,
    SelfConsistentPowerFitResult,
    SoftIntervalPenalty,
    SquaredLoss,
    UnaccountedRealizedPair,
    UnaccountedRealizedPairError,
    build_active_set_report,
    build_fit_report,
    build_power_fit_problem,
    build_power_fit_result,
    build_realized_report,
    dumps_report_json,
    fit_power_weights,
    match_realized_pairs,
    radii_to_weights,
    resolve_pair_bisector_constraints,
    solve_self_consistent_power_weights,
    weights_to_radii,
    write_report_json,
)

warn(
    'pyvoro2.powerfit is deprecated; use pyvoro2.inverse for fixed-observation '
    'separator fitting or pyvoro2.inverse.separator for advanced workflows. '
    'The compatibility package is planned for removal in v0.8.',
    DeprecationWarning,
    # A caller-facing stack level attributes a direct import to ``__main__``,
    # where Python shows DeprecationWarning by default. Keep the warning
    # library-attributed so ordinary imports remain silent as promised.
    stacklevel=1,
)

__all__ = [
    'PairBisectorConstraints',
    'resolve_pair_bisector_constraints',
    'SquaredLoss',
    'HuberLoss',
    'Interval',
    'FixedValue',
    'SoftIntervalPenalty',
    'ExponentialBoundaryPenalty',
    'ReciprocalBoundaryPenalty',
    'L2Regularization',
    'FitModel',
    'AlgebraicEdgeDiagnostics',
    'ConstraintGraphDiagnostics',
    'ConnectivityDiagnostics',
    'ConnectivityDiagnosticsError',
    'HardConstraintConflictTerm',
    'HardConstraintConflict',
    'PowerFitBounds',
    'PowerFitPredictions',
    'PowerFitObjectiveBreakdown',
    'PowerFitProblem',
    'PowerWeightFitResult',
    'build_power_fit_problem',
    'build_power_fit_result',
    'RealizedPairDiagnostics',
    'UnaccountedRealizedPair',
    'UnaccountedRealizedPairError',
    'build_fit_report',
    'build_realized_report',
    'build_active_set_report',
    'dumps_report_json',
    'write_report_json',
    'ActiveSetOptions',
    'ActiveSetIteration',
    'ActiveSetPathSummary',
    'PairConstraintDiagnostics',
    'SelfConsistentPowerFitResult',
    'fit_power_weights',
    'match_realized_pairs',
    'solve_self_consistent_power_weights',
    'radii_to_weights',
    'weights_to_radii',
]
